export const CLICK_BUTTON1='CLICK_BUTTON1';
export const CHANGE_TEXT='CHANGE_TEXT';

export const INTERRUPTION_TYPE='INTERRUPTION_TYPE';

export const INTERRUPTION_ID_BS='INTERRUPTION_ID_BS';
export const INTERRUPTION_CODE='INTERRUPTION_CODE';
export const INTERRUPTION_BS='INTERRUPTION_BS';
export const INTERRUPTION_PROVINCE='INTERRUPTION_PROVINCE';
export const INTERRUPTION_CANTON="INTERRUPTION_CANTON";
export const INTERRUPTION_PARISH="INTERRUPTION_PARISH";
export const INTERRUPTION_SECTOR="INTERUPTION_SECTOR";

export const INTERRUPTION_START="INTERRUPTION_START";
export const INTERRUPTION_END="INTERRUPTION_END";
export const INTERRUPTION_TIME="INTERRUPTION_TIME";

export const INTERRUPTION_CAUSES="INTERRUPTION_CAUSES";
export const INTERRUPTION_TAGS="INTERRUPTION_TAGS";

export const INTERRUPTION_ANNEX="INTERRUPTION_ANNEX";

export const UPDATE_INPUT_VALUE_ID = 'UPDATE_INPUT_VALUE_ID';
export const CLEAR_SUGGESTIONS_ID = 'CLEAR_SUGGESTIONS_ID';
export const MAYBE_UPDATE_SUGGESTIONS_ID = 'MAYBE_UPDATE_SUGGESTIONS_ID';
export const LOAD_SUGGESTIONS_BEGIN_ID = 'LOAD_SUGGESTIONS_BEGIN_ID';

export const UPDATE_INPUT_VALUE_EST = 'UPDATE_INPUT_VALUE_EST';
export const CLEAR_SUGGESTIONS_EST = 'CLEAR_SUGGESTIONS_EST';
export const MAYBE_UPDATE_SUGGESTIONS_EST = 'MAYBE_UPDATE_SUGGESTIONS_EST';
export const LOAD_SUGGESTIONS_BEGIN_EST = 'LOAD_SUGGESTIONS_BEGIN_EST';

export const ID_REQUEST_PENDING='ID_REQUEST_PENDING';
export const ID_REQUEST_SUCCESS='ID_REQUEST_SUCCESS';
export const ID_REQUEST_FAILED='ID_REQUEST_FAILED';

export const INTERRUPTION_SUBMITED='INTERRUPTION_SUBMITED';

export const SESSION_LOGOUT='SESSION_LOGOUT';
export const SESSION_INIT='SESSION_INIT';
export const DATA_USER = 'DATA_USER';