export const CLICK_BUTTON1='CLICK_BUTTON1';
export const CHANGE_TEXT='CHANGE_TEXT';

export const INTERRUPTION_TYPE='INTERRUPTION_TYPE';

export const INTERRUPTION_ID_BS='INTERRUPTION_ID_BS';
export const INTERRUPTION_CODE='INTERRUPTION_CODE';
export const INTERRUPTION_BS='INTERRUPTION_BS';
export const INTERRUPTION_CODE_EST='INTERRUPTION_CODE_EST';
export const INTERRUPTION_LEVEL_SELECTED="INTERRUPTION_LEVEL_SELECTED";
export const INTERRUPTION_PROVINCE='INTERRUPTION_PROVINCE';
export const INTERRUPTION_CANTON="INTERRUPTION_CANTON";
export const INTERRUPTION_PARISH="INTERRUPTION_PARISH";
export const INTERRUPTION_SECTOR="INTERUPTION_SECTOR";

export const INTERRUPTION_SERVICE_ADD="INTERRUPTION_SERVICE_ADD";
export const INTERRUPTION_SERVICE_REMOVE="INTERRUPTION_SERVICE_REMOVE";
export const INTERRUPTION_SERVICE_REMOVE_ALL="INTERRUPTION_SERVICE_REMOVE_ALL";
export const INTERRUPTION_TECHNOLOGY_ADD="INTERRUPTION_TECHNOLOGY_ADD";
export const INTERRUPTION_TECHNOLOGY_REMOVE="INTERRUPTION_TECHNOLOGY_REMOVE";
export const INTERRUPTION_TECHNOLOGY_REMOVE_ALL="INTERRUPTION_TECHNOLOGY_REMOVE_ALL";

export const INTERRUPTION_START="INTERRUPTION_START";
export const INTERRUPTION_END="INTERRUPTION_END";
export const INTERRUPTION_TIME="INTERRUPTION_TIME";

export const INTERRUPTION_CAUSES="INTERRUPTION_CAUSES";
export const INTERRUPTION_TAGS="INTERRUPTION_TAGS";

export const INTERRUPTION_ANNEX="INTERRUPTION_ANNEX";

export const UPDATE_INPUT_VALUE_ID = 'UPDATE_INPUT_VALUE_ID';
export const CLEAR_SUGGESTIONS_ID = 'CLEAR_SUGGESTIONS_ID';
export const MAYBE_UPDATE_SUGGESTIONS_ID = 'MAYBE_UPDATE_SUGGESTIONS_ID';
export const LOAD_SUGGESTIONS_BEGIN_ID = 'LOAD_SUGGESTIONS_BEGIN_ID';

export const UPDATE_INPUT_VALUE_EST = 'UPDATE_INPUT_VALUE_EST';
export const CLEAR_SUGGESTIONS_EST = 'CLEAR_SUGGESTIONS_EST';
export const MAYBE_UPDATE_SUGGESTIONS_EST = 'MAYBE_UPDATE_SUGGESTIONS_EST';
export const LOAD_SUGGESTIONS_BEGIN_EST = 'LOAD_SUGGESTIONS_BEGIN_EST';

export const UPDATE_INPUT_VALUE_COD_EST = 'UPDATE_INPUT_VALUE_COD_EST';
export const CLEAR_SUGGESTIONS_COD_EST = 'CLEAR_SUGGESTIONS_COD_EST';
export const MAYBE_UPDATE_SUGGESTIONS_COD_EST = 'MAYBE_UPDATE_SUGGESTIONS_COD_EST';
export const LOAD_SUGGESTIONS_BEGIN_COD_EST = 'LOAD_SUGGESTIONS_BEGIN_COD_EST';

export const UPDATE_INPUT_VALUE_PROVINCE = 'UPDATE_INPUT_VALUE_PROVINCE';
export const CLEAR_SUGGESTIONS_PROVINCE = 'CLEAR_SUGGESTIONS_PROVINCE';
export const MAYBE_UPDATE_SUGGESTIONS_PROVINCE = 'MAYBE_UPDATE_SUGGESTIONS_PROVINCE';
export const LOAD_SUGGESTIONS_BEGIN_PROVINCE = 'LOAD_SUGGESTIONS_BEGIN_PROVINCE';

export const UPDATE_INPUT_VALUE_CANTON = 'UPDATE_INPUT_VALUE_CANTON';
export const CLEAR_SUGGESTIONS_CANTON = 'CLEAR_SUGGESTIONS_CANTON';
export const MAYBE_UPDATE_SUGGESTIONS_CANTON = 'MAYBE_UPDATE_SUGGESTIONS_CANTON';
export const LOAD_SUGGESTIONS_BEGIN_CANTON = 'LOAD_SUGGESTIONS_BEGIN_CANTON';

export const UPDATE_INPUT_VALUE_PARISH = 'UPDATE_INPUT_VALUE_PARISH';
export const CLEAR_SUGGESTIONS_PARISH = 'CLEAR_SUGGESTIONS_PARISH';
export const MAYBE_UPDATE_SUGGESTIONS_PARISH = 'MAYBE_UPDATE_SUGGESTIONS_PARISH';
export const LOAD_SUGGESTIONS_BEGIN_PARISH = 'LOAD_SUGGESTIONS_BEGIN_PARISH';

export const ID_REQUEST_PENDING='ID_REQUEST_PENDING';
export const ID_REQUEST_SUCCESS='ID_REQUEST_SUCCESS';
export const ID_REQUEST_FAILED='ID_REQUEST_FAILED';

export const ADDRESS_REQUEST_PENDING='ADDRESS_REQUEST_PENDING';
export const ADDRESS_REQUEST_SUCCESS='ADDRESS_REQUEST_SUCCESS';
export const ADDRESS_REQUEST_FAILED='ADDRESS_REQUEST_FAILED';

export const PROVINCE_REQUEST_PENDING='PROVINCE_REQUEST_PENDING';
export const PROVINCE_REQUEST_SUCCESS='PROVINCE_REQUEST_SUCCESS';
export const PROVINCE_REQUEST_FAILED='PROVINCE_REQUEST_FAILED';

export const CANTON_REQUEST_PENDING='CANTON_REQUEST_PENDING';
export const CANTON_REQUEST_SUCCESS='CANTON_REQUEST_SUCCESS';
export const CANTON_REQUEST_FAILED='CANTON_REQUEST_FAILED';

export const PARISH_REQUEST_PENDING='PARISH_REQUEST_PENDING';
export const PARISH_REQUEST_SUCCESS='PARISH_REQUEST_SUCCESS';
export const PARISH_REQUEST_FAILED='PARISH_REQUEST_FAILED';

export const INTERRUPTION_SUBMITED='INTERRUPTION_SUBMITED';

export const SESSION_LOGOUT='SESSION_LOGOUT';
export const SESSION_INIT='SESSION_INIT';
export const DATA_USER = 'DATA_USER';

export const RADIOBASES_SELECTED='RADIOBASES_SELECTED';
export const RADIOBASES_REMOVE='RADIOBASES_REMOVE';
export const RADIOBASES_REMOVE_ALL='RADIOBASES_REMOVE_ALL';

export const RADIOBASES_ID_SELECTED='RADIOBASES_ID_SELECTED';
export const RADIOBASES_ID_REMOVE='RADIOBASES_ID_REMOVE';
export const RADIOBASES_ID_REMOVE_ALL='RADIOBASES_ID_REMOVE_ALL';