export const CLICK_BUTTON1='CLICK_BUTTON1';
export const CHANGE_TEXT='CHANGE_TEXT';

export const INTERRUPTION_TYPE='INTERRUPTION_TYPE';

export const INTERRUPTION_CODE='INTERRUPTION_CODE';
export const INTERRUPTION_BS='INTERRUPTION_BS';
export const INTERRUPTION_PROVINCE='INTERRUPTION_PROVINCE';
export const INTERRUPTION_CANTON="INTERRUPTION_CANTON";
export const INTERRUPTION_PARISH="INTERRUPTION_PARISH";
export const INTERRUPTION_SECTOR="INTERUPTION_SECTOR";

export const INTERRUPTION_START="INTERRUPTION_START";
export const INTERRUPTION_END="INTERRUPTION_END";
export const INTERRUPTION_TIME="INTERRUPTION_TIME";

export const INTERRUPTION_CAUSES="INTERRUPTION_CAUSES";

export const INTERRUPTION_ANNEX="INTERRUPTION_ANNEX";